name: build

on: [push, pull_request]

jobs:
  build:
    name: build (${{ matrix.ruby }}
    strategy:
      matrix:
        ruby: [ 3.0, 2.7, head ]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: bundle install
    - name: Run test
      run: rake test
